### ISSUE TITLE
Issues using tiny-webcrypto in CommonJS Node libraries

### ISSUE THREAD

**Issue by MasterKale** [fabiospampinato/tiny-webcrypto#1]
First off, thank you for offering a potentially easier path forward for writing isomorphic libraries using the WebCrypto API.

I'm having an issue with a [large rewrite of my @simplewebauthn/server Node library](https://github.com/MasterKale/SimpleWebAuthn/pull/299), trying to make it work in more than just Node. Unfortunately, after outputting a CommonJS build of my library, attempts to use my library error out because tiny-webcrypto's build seems to only output ESM:

```
/Users/matt/Developer/simplewebauthn/packages/server/dist/helpers/iso/isoCrypto/digest.js:7
const tiny_webcrypto_1 = __importDefault(require("tiny-webcrypto"));
                                         ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/matt/Developer/simplewebauthn/packages/server/
  node_modules/tiny-webcrypto/dist/node.js from /Users/matt/Developer/simplewebauthn/packages/server/
  dist/helpers/iso/isoCrypto/digest.js not supported.
Instead change the require of node.js in /Users/matt/Developer/simplewebauthn/packages/server/dist/helpers/iso/
  isoCrypto/digest.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/matt/Developer/simplewebauthn/packages/server/dist/helpers/iso/isoCrypto/digest.js:7:42)
    at Object.<anonymous> (/Users/matt/Developer/simplewebauthn/packages/server/dist/helpers/iso/isoCrypto/index.js:4:16)
    at Object.<anonymous> (/Users/matt/Developer/simplewebauthn/packages/server/dist/helpers/iso/index.js:36:34)
    at Object.<anonymous> (/Users/matt/Developer/simplewebauthn/packages/server/dist/helpers/generateChallenge.js:4:15)
    at Object.<anonymous> (/Users/matt/Developer/simplewebauthn/packages/server/dist/registration/generateRegistrationOptions.js:4:29)
    at Object.<anonymous> (/Users/matt/Developer/simplewebauthn/packages/server/dist/index.js:8:39)
    at Object.<anonymous> (/Users/matt/Developer/simplewebauthn/example/index.ts:43:18)
    at Module.m._compile (/Users/matt/Developer/simplewebauthn/example/node_modules/ts-node/dist/index.js:791:29)
    at Object.require.extensions.<computed> [as .ts] (/Users/matt/Developer/simplewebauthn/example/node_modules/ts-node/dist/index.js:793:16)
    at phase4 (/Users/matt/Developer/simplewebauthn/example/node_modules/ts-node/dist/bin.js:407:16)
    at bootstrap (/Users/matt/Developer/simplewebauthn/example/node_modules/ts-node/dist/bin.js:49:12)
    at main (/Users/matt/Developer/simplewebauthn/example/node_modules/ts-node/dist/bin.js:32:12)
    at Object.<anonymous> (/Users/matt/Developer/simplewebauthn/example/node_modules/ts-node/dist/bin.js:519:5) {
  code: 'ERR_REQUIRE_ESM'
}
```

I'd rather not refactor my `WebCrypto`-consuming code to use `await import()` as suggested in the error because doing so would drastically change the API of methods that are currently synchronous by requiring they become asynchronous, and force methods that consume those methods to update their method signatures to become asynchronous as well. I'm trying to avoid making too many breaking changes like that with this rewrite.

Do you have any recommendations for how I might work past this? Is there any chance of this project including a CommonJS version for those TypeScript projects building with `"module": "commonjs"` in their **package.json**?

**Comment by fabiospampinato** [comment]
Hey, sorry about that, CJS/ESM interoperability is a total mess, for that reason I moved fully to ESM myself, I've no intention of supporting CJS anymore.

I'm not sure what the best options could be for your use case. If you can ship a bundled library maybe you can write it in ESM and then bundle it with something like esbuild to both ESM and CJS? If bundling is not ok maybe you can fork this and publish a CJS version of it 🤔 I'm not sure what else could be tried.

**Comment by fabiospampinato** [comment]
Maybe another option is this: 

1. You write a function that receives as input the webcrypto object and returns as output whatever your library returns.
2. You bundle tiny-webcrypto to both esm and cjs with esbuild.
3. You add 2 entrypoints to your package, one for node and one for the browser, that import respectively the CJS and the ESM bundled versions of tiny-webcrypto, and they pass them along to the function that gives you the API of your library.

It should work, but avoiding writing that kind of code is precisely why I wrong tiny-webcrypto.

**Comment by MasterKale** [comment]
Thank you for responding, and I totally understand your decision. I'd rather skip supporting CJS too, one of these days I'll bite the bullet and switch my project over to pure ESM too.

> If bundling is not ok maybe you can fork this and publish a CJS version of it 🤔

I ended up going this route. I'm vendoring tiny-webcrypto into my monorepo as a new ["@simplewebauthn/iso-webcrypto"](https://github.com/MasterKale/SimpleWebAuthn/pull/299/commits/86adf04b351d160532eeb9b5f6e07ec45707a15e) that I'll maintain and deal with the CommonJS headaches instead.
